import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  s5Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  s6Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
